In [2]:
import pandas as pd
import os
os.chdir(r'C:\Users\ARSHAN\Desktop\Data science Projects')
sal=pd.read_csv('salariesDT.csv')
sal.head()
col=['Unnamed: 4']
sal.drop(col,inplace=True,axis=1)
sal.head()


company                  job     degree  salary_more_then_100k
0  google      sales executive  bachelors                      0
1  google      sales executive    masters                      0
2  google     business manager  bachelors                      1
3  google     business manager    masters                      1
4  google  computer programmer  bachelors                      0

In [11]:
#dropping target variable from dataframe
inputs=sal.drop('salary_more_then_100k',axis=1)
target=sal['salary_more_then_100k']

In [13]:
inputs.head()
target.tail()

11    1
12    1
13    1
14    1
15    1
Name: salary_more_then_100k, dtype: int64

In [14]:
#ML algorithms works only on numbers so we need to us encoder from sklearn
from sklearn.preprocessing import LabelEncoder

In [21]:
#encoding our labels
le_company = LabelEncoder()
le_job = LabelEncoder()
le_degree = LabelEncoder()

In [24]:
#transforming encoded labels by creating additional columns in the dataframe
inputs['company_n']=le_company.fit_transform(inputs['company'])
inputs['job_n']=le_job.fit_transform(inputs['job'])
inputs['degree_n']=le_degree.fit_transform(inputs['degree'])
inputs

company                  job     degree  company_n  job_n  degree_n
0       google      sales executive  bachelors          2      2         0
1       google      sales executive    masters          2      2         1
2       google     business manager  bachelors          2      0         0
3       google     business manager    masters          2      0         1
4       google  computer programmer  bachelors          2      1         0
5       google  computer programmer    masters          2      1         1
6   abc pharma      sales executive    masters          0      2         1
7   abc pharma  computer programmer  bachelors          0      1         0
8   abc pharma     business manager  bachelors          0      0         0
9   abc pharma     business manager    masters          0      0         1
10    facebook      sales executive  bachelors          1      2         0
11    facebook      sales executive    masters          1      2         1
12    facebook     business manager  bachelors          1      0         0
13    facebook     business manager    masters          1      0         1
14    facebook  computer programmer  bachelors          1      1         0
15    facebook  computer programmer    masters          1      1         1

In [26]:
inputs_n=inputs.drop(['company','job','degree'],axis=1)
inputs_n
#here google encoded as 2, Facebook encoded as 1, ABC pharma encoded as 0
#now we are ready to train our classifier since we have both target and label variables encoded 

company_n  job_n  degree_n
0           2      2         0
1           2      2         1
2           2      0         0
3           2      0         1
4           2      1         0
5           2      1         1
6           0      2         1
7           0      1         0
8           0      0         0
9           0      0         1
10          1      2         0
11          1      2         1
12          1      0         0
13          1      0         1
14          1      1         0
15          1      1         1

In [115]:
from sklearn import tree
from sklearn.tree import DecisionTreeClassifier

In [30]:
model= tree.DecisionTreeClassifier()

In [31]:
model.fit(inputs_n,target)

DecisionTreeClassifier(class_weight=None, criterion='gini', max_depth=None,
            max_features=None, max_leaf_nodes=None,
            min_impurity_decrease=0.0, min_impurity_split=None,
            min_samples_leaf=1, min_samples_split=2,
            min_weight_fraction_leaf=0.0, presort=False, random_state=None,
            splitter='best')

In [34]:
model.score(inputs_n,target)

1.0

In [38]:
model.predict([[2,0,1]])

array([1], dtype=int64)

on titanic dataset
predicting the survival of a passenger using class sex age and fare

In [16]:
import pandas as pd
from sklearn.preprocessing import LabelEncoder
from sklearn import tree
from sklearn.tree import DecisionTreeClassifier
tit=pd.read_csv('titanic.csv')
tit.head()
tit
target=tit['Survived']
target.head()

0    0
1    1
2    1
3    1
4    0
Name: Survived, dtype: int64

In [17]:
#checing missing values in dataframe 
tit.isnull().sum()/tit.count().sum()

PassengerId    0.000000
Survived       0.000000
Pclass         0.000000
Name           0.000000
Sex            0.000000
Age            0.018013
SibSp          0.000000
Parch          0.000000
Ticket         0.000000
Fare           0.000000
Cabin          0.069917
Embarked       0.000204
dtype: float64

In [18]:
#since less than 10% values are there we are going to remove all of it
tit=tit.dropna(axis=0, how="any", thresh=None, subset=None, inplace=False)
tit.isnull().sum()/tit.count().sum()

PassengerId    0.0
Survived       0.0
Pclass         0.0
Name           0.0
Sex            0.0
Age            0.0
SibSp          0.0
Parch          0.0
Ticket         0.0
Fare           0.0
Cabin          0.0
Embarked       0.0
dtype: float64

In [19]:
#dropping target variable from dataframe
target=tit[['Survived']]
tit=tit.drop('Survived',axis=1)
tit.head()
target.head()

Survived
1          1
3          1
6          0
10         1
11         1

In [20]:
#dropping other non essential variables and creating input dataframe
inputs=tit.drop(['Name','SibSp','Parch','Ticket','Cabin','Embarked'],axis=1)
inputs.tail()

PassengerId  Pclass     Sex   Age     Fare
871          872       1  female  47.0  52.5542
872          873       1    male  33.0   5.0000
879          880       1  female  56.0  83.1583
887          888       1  female  19.0  30.0000
889          890       1    male  26.0  30.0000

In [21]:
#converting string variables to numeric using LabelEncoder
le_Sex= LabelEncoder()
inputs['Sex_n']=le_Sex.fit_transform(tit['Sex'])


In [22]:
#replacing that in dataframe
inputs=inputs.drop('Sex',axis=1)
inputs.head()

PassengerId  Pclass   Age     Fare  Sex_n
1             2       1  38.0  71.2833      0
3             4       1  35.0  53.1000      0
6             7       1  54.0  51.8625      1
10           11       3   4.0  16.7000      0
11           12       1  58.0  26.5500      0

In [23]:
#checing missing values in dataframe
inputs.isnull().sum()/inputs.count().sum()

PassengerId    0.0
Pclass         0.0
Age            0.0
Fare           0.0
Sex_n          0.0
dtype: float64

In [24]:
inputs.head()

PassengerId  Pclass   Age     Fare  Sex_n
1             2       1  38.0  71.2833      0
3             4       1  35.0  53.1000      0
6             7       1  54.0  51.8625      1
10           11       3   4.0  16.7000      0
11           12       1  58.0  26.5500      0

In [25]:
inputs.isnull().sum()/inputs.count().sum()

PassengerId    0.0
Pclass         0.0
Age            0.0
Fare           0.0
Sex_n          0.0
dtype: float64

In [36]:
model=tree.DecisionTreeClassifier()
model.fit(inputs,target)
model.score(xtrain,ytrain)

NameError: name 'xtrain' is not defined

In [39]:
#now lets train our classifier
from sklearn.model_selection import train_test_split
x_train,x_test,y_train,y_test=train_test_split(inputs,target,test_size=0.3,stratify=target,random_state=100)
y_train.head()

Survived
92          0
806         0
139         0
516         1
544         0

In [44]:
model=tree.DecisionTreeClassifier()
model.fit(x_train,y_train)
clf_gini.score(x_train,y_train)

0.828125

In [52]:
clf_gini.score(x_test,y_test)

0.7272727272727273

In [43]:
clf_gini = DecisionTreeClassifier(criterion='gini',random_state=100,max_depth=3,min_samples_leaf=5)
clf_gini.fit(x_train,y_train)

DecisionTreeClassifier(class_weight=None, criterion='gini', max_depth=3,
            max_features=None, max_leaf_nodes=None,
            min_impurity_decrease=0.0, min_impurity_split=None,
            min_samples_leaf=5, min_samples_split=2,
            min_weight_fraction_leaf=0.0, presort=False, random_state=100,
            splitter='best')

In [29]:
y_pred=clf_gini.predict(x_test)
y_pred


array([1, 1, 1, 1, 1, 0, 1, 0, 1, 0, 1, 1, 1, 1, 1, 1, 0, 1, 0, 0, 1, 1,
       0, 1, 1, 1, 1, 0, 0, 0, 1, 0, 1, 1, 0, 1, 1, 1, 1, 1, 0, 0, 1, 1,
       1, 1, 1, 0, 1, 1, 0, 1, 1, 0, 1], dtype=int64)

In [30]:
from sklearn.metrics import confusion_matrix
import numpy as np
c=confusion_matrix(y_test,y_pred)
np.sum(c)
accuracy=(c[0,0]+c[1,1])/np.sum(c)
print('accuracy of model is :',accuracy*100)


accuracy of model is : 72.72727272727273


In [45]:
confusion_matrix.score(y_test,y_pred)

AttributeError: 'function' object has no attribute 'score'

In [46]:
from sklearn.tree import DecisionTreeRegressor
model=DecisionTreeRegressor(max_depth=3,min_samples_leaf=5)
model.fit(x_train,y_train)
help.(model.score)

SyntaxError: invalid syntax (<ipython-input-46-7d267318ce04>, line 4)

In [34]:
y_pred=model.predict(x_test)
y_pred

array([0.97959184, 0.97959184, 0.97959184, 0.74074074, 0.97959184,
       0.36842105, 0.97959184, 0.36842105, 0.97959184, 0.36842105,
       0.97959184, 0.74074074, 0.97959184, 0.8       , 0.97959184,
       0.97959184, 0.125     , 0.74074074, 0.125     , 0.125     ,
       0.74074074, 0.97959184, 0.36842105, 0.97959184, 0.74074074,
       0.97959184, 0.97959184, 0.36842105, 0.36842105, 0.125     ,
       0.74074074, 0.36842105, 0.97959184, 0.74074074, 0.36842105,
       0.6       , 0.74074074, 0.97959184, 0.97959184, 0.97959184,
       0.125     , 0.125     , 0.97959184, 0.97959184, 0.6       ,
       0.74074074, 0.97959184, 0.125     , 0.97959184, 0.6       ,
       0.28571429, 0.97959184, 0.6       , 0.125     , 0.97959184])

In [35]:

rmse1=np.sqrt(np.mean((np.array(y_test)-y_pred)**2))#RMSE
rmse1

0.5679100121107226